### ISSUE TITLE
No module named 'mne.externals'

### ISSUE THREAD

**Issue by BarryLiu97** [mne-tools/mne-hfo#53]
Hi, I found when I used the dev version of mne, this error would come out.
```
Traceback (most recent call last):
    from mne_hfo import LineLengthDetector, RMSDetector, events_to_annotations, compute_chs_hfo_rates
  File "D:\ProgramData\Miniconda3\lib\site-packages\mne_hfo\__init__.py", line 5, in <module>
    from mne_hfo.detect import RMSDetector, LineLengthDetector, HilbertDetector
  File "D:\ProgramData\Miniconda3\lib\site-packages\mne_hfo\detect.py", line 6, in <module>
    from mne_hfo.base import Detector
  File "D:\ProgramData\Miniconda3\lib\site-packages\mne_hfo\base.py", line 13, in <module>
    from mne_hfo.io import create_events_df, events_to_annotations
  File "D:\ProgramData\Miniconda3\lib\site-packages\mne_hfo\io.py", line 12, in <module>
    from mne_bids import read_raw_bids, get_entities_from_fname, BIDSPath
  File "D:\ProgramData\Miniconda3\lib\site-packages\mne_bids\__init__.py", line 5, in <module>
    from mne_bids.report import make_report
  File "D:\ProgramData\Miniconda3\lib\site-packages\mne_bids\report.py", line 11, in <module>
    from mne.externals.tempita import Template
ModuleNotFoundError: No module named 'mne.externals'
```

**Comment by BarryLiu97** [comment]
OK, I just found this is a mne-bids issue. I solved this by installing  the dev version of mne-bids.
